[2022-05-28 18:07:04,873] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T16:06:00+00:00 [queued]>
[2022-05-28 18:07:04,881] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T16:06:00+00:00 [queued]>
[2022-05-28 18:07:04,881] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:07:04,881] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 18:07:04,881] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:07:04,896] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_quotation_from_TSLA> on 2022-05-28 16:06:00+00:00
[2022-05-28 18:07:04,897] {standard_task_runner.py:52} INFO - Started process 21669 to run task
[2022-05-28 18:07:04,900] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'quotation_dag', 'fetch_quotation_from_TSLA', 'scheduled__2022-05-28T16:06:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/load_quotation_dag.py', '--cfg-path', '/tmp/tmp7p166p_d', '--error-file', '/tmp/tmpq_nh7_c3']
[2022-05-28 18:07:04,901] {standard_task_runner.py:80} INFO - Job 194: Subtask fetch_quotation_from_TSLA
[2022-05-28 18:07:04,944] {logging_mixin.py:109} INFO - Running <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T16:06:00+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 18:07:04,992] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=quotation_dag
AIRFLOW_CTX_TASK_ID=fetch_quotation_from_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T16:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T16:06:00+00:00
[2022-05-28 18:07:05,007] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 18:07:05,007] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 24, in push_quotation_on_datalake
    quotation = fetch_quotation_from_big_finance(company)
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 13, in fetch_quotation_from_big_finance
    date_from = kwargs['dag_run'].conf.get('date_from')
KeyError: 'dag_run'
[2022-05-28 18:07:05,013] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=quotation_dag, task_id=fetch_quotation_from_TSLA, execution_date=20220528T160600, start_date=20220528T160704, end_date=20220528T160705
[2022-05-28 18:07:05,026] {standard_task_runner.py:93} ERROR - Failed to execute job 194 for task fetch_quotation_from_TSLA ('dag_run'; 21669)
[2022-05-28 18:07:05,032] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-28 18:07:05,047] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
