[2022-05-28 18:03:04,310] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T16:02:00+00:00 [queued]>
[2022-05-28 18:03:04,314] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T16:02:00+00:00 [queued]>
[2022-05-28 18:03:04,314] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:03:04,314] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 18:03:04,314] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:03:04,327] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_quotation_from_TSLA> on 2022-05-28 16:02:00+00:00
[2022-05-28 18:03:04,328] {standard_task_runner.py:52} INFO - Started process 20685 to run task
[2022-05-28 18:03:04,330] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'quotation_dag', 'fetch_quotation_from_TSLA', 'scheduled__2022-05-28T16:02:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/load_quotation_dag.py', '--cfg-path', '/tmp/tmp272qpcr_', '--error-file', '/tmp/tmpg0dja7qk']
[2022-05-28 18:03:04,331] {standard_task_runner.py:80} INFO - Job 176: Subtask fetch_quotation_from_TSLA
[2022-05-28 18:03:04,358] {logging_mixin.py:109} INFO - Running <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T16:02:00+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 18:03:04,394] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=quotation_dag
AIRFLOW_CTX_TASK_ID=fetch_quotation_from_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T16:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T16:02:00+00:00
[2022-05-28 18:03:04,406] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 18:03:04,406] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 25, in push_quotation_on_datalake
    quotation = fetch_quotation_from_big_finance()
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 13, in fetch_quotation_from_big_finance
    company = kwargs['company']
KeyError: 'company'
[2022-05-28 18:03:04,411] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=quotation_dag, task_id=fetch_quotation_from_TSLA, execution_date=20220528T160200, start_date=20220528T160304, end_date=20220528T160304
[2022-05-28 18:03:04,424] {standard_task_runner.py:93} ERROR - Failed to execute job 176 for task fetch_quotation_from_TSLA ('company'; 20685)
[2022-05-28 18:03:04,462] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-28 18:03:04,474] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
