[2022-05-28 17:54:04,308] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T15:53:00+00:00 [queued]>
[2022-05-28 17:54:04,312] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T15:53:00+00:00 [queued]>
[2022-05-28 17:54:04,312] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 17:54:04,312] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 17:54:04,312] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 17:54:04,333] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_quotation_from_TSLA> on 2022-05-28 15:53:00+00:00
[2022-05-28 17:54:04,334] {standard_task_runner.py:52} INFO - Started process 19016 to run task
[2022-05-28 17:54:04,336] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'quotation_dag', 'fetch_quotation_from_TSLA', 'scheduled__2022-05-28T15:53:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/load_quotation_dag.py', '--cfg-path', '/tmp/tmpn5e3_r6q', '--error-file', '/tmp/tmpr6yeunpd']
[2022-05-28 17:54:04,337] {standard_task_runner.py:80} INFO - Job 146: Subtask fetch_quotation_from_TSLA
[2022-05-28 17:54:04,365] {logging_mixin.py:109} INFO - Running <TaskInstance: quotation_dag.fetch_quotation_from_TSLA scheduled__2022-05-28T15:53:00+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 17:54:04,404] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=quotation_dag
AIRFLOW_CTX_TASK_ID=fetch_quotation_from_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T15:53:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T15:53:00+00:00
[2022-05-28 17:54:04,404] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: fetch_quotation_from_big_finance() missing 2 required positional arguments: 'date_from' and 'date_to'
[2022-05-28 17:54:04,407] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=quotation_dag, task_id=fetch_quotation_from_TSLA, execution_date=20220528T155300, start_date=20220528T155404, end_date=20220528T155404
[2022-05-28 17:54:04,422] {standard_task_runner.py:93} ERROR - Failed to execute job 146 for task fetch_quotation_from_TSLA (fetch_quotation_from_big_finance() missing 2 required positional arguments: 'date_from' and 'date_to'; 19016)
[2022-05-28 17:54:04,428] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-28 17:54:04,438] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
