[2022-05-28 18:12:05,717] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_GOOGL scheduled__2022-05-28T16:11:00+00:00 [queued]>
[2022-05-28 18:12:05,722] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_GOOGL scheduled__2022-05-28T16:11:00+00:00 [queued]>
[2022-05-28 18:12:05,722] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:12:05,722] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 18:12:05,722] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:12:05,733] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_quotation_from_GOOGL> on 2022-05-28 16:11:00+00:00
[2022-05-28 18:12:05,734] {standard_task_runner.py:52} INFO - Started process 22826 to run task
[2022-05-28 18:12:05,737] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'quotation_dag', 'fetch_quotation_from_GOOGL', 'scheduled__2022-05-28T16:11:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/load_quotation_dag.py', '--cfg-path', '/tmp/tmpsr08fry6', '--error-file', '/tmp/tmpalrdc4cd']
[2022-05-28 18:12:05,737] {standard_task_runner.py:80} INFO - Job 214: Subtask fetch_quotation_from_GOOGL
[2022-05-28 18:12:05,765] {logging_mixin.py:109} INFO - Running <TaskInstance: quotation_dag.fetch_quotation_from_GOOGL scheduled__2022-05-28T16:11:00+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 18:12:05,799] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=quotation_dag
AIRFLOW_CTX_TASK_ID=fetch_quotation_from_GOOGL
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T16:11:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T16:11:00+00:00
[2022-05-28 18:12:05,811] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 18:12:06,369] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 24, in push_quotation_on_datalake
    quotation = fetch_quotation_from_big_finance(company, date_from, date_to)
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 14, in fetch_quotation_from_big_finance
    response = get(f"https://bigfinance-api.herokuapp.com/stockdata/api/v1/intraday/{company}/{date_from}/{date_to}/", headers=header).json()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
: 1
[2022-05-28 18:12:06,374] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=quotation_dag, task_id=fetch_quotation_from_GOOGL, execution_date=20220528T161100, start_date=20220528T161205, end_date=20220528T161206
[2022-05-28 18:12:06,387] {standard_task_runner.py:93} ERROR - Failed to execute job 214 for task fetch_quotation_from_GOOGL ([Errno Expecting value] 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
: 1; 22826)
[2022-05-28 18:12:06,391] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-28 18:12:06,402] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
