[2022-05-28 18:44:05,955] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: recommendation_dag.fetch_recommendation_from_TSLA scheduled__2022-05-27T16:43:56.388496+00:00 [queued]>
[2022-05-28 18:44:05,959] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: recommendation_dag.fetch_recommendation_from_TSLA scheduled__2022-05-27T16:43:56.388496+00:00 [queued]>
[2022-05-28 18:44:05,959] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:44:05,959] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 18:44:05,959] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:44:05,979] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_recommendation_from_TSLA> on 2022-05-27 16:43:56.388496+00:00
[2022-05-28 18:44:05,980] {standard_task_runner.py:52} INFO - Started process 25427 to run task
[2022-05-28 18:44:05,982] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'recommendation_dag', 'fetch_recommendation_from_TSLA', 'scheduled__2022-05-27T16:43:56.388496+00:00', '--job-id', '223', '--raw', '--subdir', 'DAGS_FOLDER/load_recommendation_dag.py', '--cfg-path', '/tmp/tmpvumu4pjk', '--error-file', '/tmp/tmp6a6mfhxo']
[2022-05-28 18:44:05,983] {standard_task_runner.py:80} INFO - Job 223: Subtask fetch_recommendation_from_TSLA
[2022-05-28 18:44:06,021] {logging_mixin.py:109} INFO - Running <TaskInstance: recommendation_dag.fetch_recommendation_from_TSLA scheduled__2022-05-27T16:43:56.388496+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 18:44:06,057] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=recommendation_dag
AIRFLOW_CTX_TASK_ID=fetch_recommendation_from_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2022-05-27T16:43:56.388496+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-27T16:43:56.388496+00:00
[2022-05-28 18:44:06,068] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 18:44:06,435] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/udimini/airflow/dags/load_recommendation_dag.py", line 24, in push_recommendation_on_datalake
    recommendations = fetch_recommendation_from_big_finance(company, date_from, date_to)
  File "/home/udimini/airflow/dags/load_recommendation_dag.py", line 14, in fetch_recommendation_from_big_finance
    response = get(f"https://bigfinance-api.herokuapp.com/finnhub/api/v1/recommendation/{company}/{date_from}/{date_to}/", headers=header).json()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
: 1
[2022-05-28 18:44:06,447] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=recommendation_dag, task_id=fetch_recommendation_from_TSLA, execution_date=20220527T164356, start_date=20220528T164405, end_date=20220528T164406
[2022-05-28 18:44:06,465] {standard_task_runner.py:93} ERROR - Failed to execute job 223 for task fetch_recommendation_from_TSLA ([Errno Expecting value] 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
: 1; 25427)
[2022-05-28 18:44:06,478] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-28 18:44:06,488] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
