[2022-05-28 19:44:13,147] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: news_dag.fetch_news_from_AAPL scheduled__2022-05-27T17:44:09.307870+00:00 [queued]>
[2022-05-28 19:44:13,157] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: news_dag.fetch_news_from_AAPL scheduled__2022-05-27T17:44:09.307870+00:00 [queued]>
[2022-05-28 19:44:13,158] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 19:44:13,158] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 19:44:13,158] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 19:44:13,170] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_news_from_AAPL> on 2022-05-27 17:44:09.307870+00:00
[2022-05-28 19:44:13,171] {standard_task_runner.py:52} INFO - Started process 31911 to run task
[2022-05-28 19:44:13,174] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'news_dag', 'fetch_news_from_AAPL', 'scheduled__2022-05-27T17:44:09.307870+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/load_news_dag.py', '--cfg-path', '/tmp/tmp11k0kehp', '--error-file', '/tmp/tmp74whhhb8']
[2022-05-28 19:44:13,174] {standard_task_runner.py:80} INFO - Job 243: Subtask fetch_news_from_AAPL
[2022-05-28 19:44:13,207] {logging_mixin.py:109} INFO - Running <TaskInstance: news_dag.fetch_news_from_AAPL scheduled__2022-05-27T17:44:09.307870+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 19:44:13,243] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=news_dag
AIRFLOW_CTX_TASK_ID=fetch_news_from_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2022-05-27T17:44:09.307870+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-27T17:44:09.307870+00:00
[2022-05-28 19:44:13,319] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 19:44:14,140] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/udimini/airflow/dags/load_news_dag.py", line 24, in push_news_on_datalake
    news = fetch_news_from_big_finance(company, date_from, date_to)
  File "/home/udimini/airflow/dags/load_news_dag.py", line 14, in fetch_news_from_big_finance
    response = get(f"https://bigfinance-api.herokuapp.com/stockdata/api/v1/news/{company}/{date_from}/{date_to}/", headers=header).json()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
: 1
[2022-05-28 19:44:14,144] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=news_dag, task_id=fetch_news_from_AAPL, execution_date=20220527T174409, start_date=20220528T174413, end_date=20220528T174414
[2022-05-28 19:44:14,156] {standard_task_runner.py:93} ERROR - Failed to execute job 243 for task fetch_news_from_AAPL ([Errno Expecting value] 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
: 1; 31911)
[2022-05-28 19:44:14,191] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-28 19:44:14,201] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
