[2022-05-28 18:05:03,829] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_GOOGL scheduled__2022-05-28T16:04:00+00:00 [queued]>
[2022-05-28 18:05:03,835] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: quotation_dag.fetch_quotation_from_GOOGL scheduled__2022-05-28T16:04:00+00:00 [queued]>
[2022-05-28 18:05:03,835] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:05:03,835] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-05-28 18:05:03,835] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-05-28 18:05:03,846] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): fetch_quotation_from_GOOGL> on 2022-05-28 16:04:00+00:00
[2022-05-28 18:05:03,848] {standard_task_runner.py:52} INFO - Started process 21087 to run task
[2022-05-28 18:05:03,850] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'quotation_dag', 'fetch_quotation_from_GOOGL', 'scheduled__2022-05-28T16:04:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/load_quotation_dag.py', '--cfg-path', '/tmp/tmpvaf7ecyu', '--error-file', '/tmp/tmpqsq4bg9m']
[2022-05-28 18:05:03,850] {standard_task_runner.py:80} INFO - Job 184: Subtask fetch_quotation_from_GOOGL
[2022-05-28 18:05:03,882] {logging_mixin.py:109} INFO - Running <TaskInstance: quotation_dag.fetch_quotation_from_GOOGL scheduled__2022-05-28T16:04:00+00:00 [running]> on host DESKTOP-O4M0F04.localdomain
[2022-05-28 18:05:03,918] {taskinstance.py:1446} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=quotation_dag
AIRFLOW_CTX_TASK_ID=fetch_quotation_from_GOOGL
AIRFLOW_CTX_EXECUTION_DATE=2022-05-28T16:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-28T16:04:00+00:00
[2022-05-28 18:05:03,992] {logging_mixin.py:109} INFO - Successful connection to mongo db
[2022-05-28 18:05:03,993] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/udimini/airflow_venv/airflow_venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 25, in push_quotation_on_datalake
    quotation = fetch_quotation_from_big_finance()
  File "/home/udimini/airflow/dags/load_quotation_dag.py", line 13, in fetch_quotation_from_big_finance
    company = kwargs['company']
KeyError: 'company'
[2022-05-28 18:05:04,009] {taskinstance.py:1278} INFO - Marking task as UP_FOR_RETRY. dag_id=quotation_dag, task_id=fetch_quotation_from_GOOGL, execution_date=20220528T160400, start_date=20220528T160503, end_date=20220528T160504
[2022-05-28 18:05:04,077] {standard_task_runner.py:93} ERROR - Failed to execute job 184 for task fetch_quotation_from_GOOGL ('company'; 21087)
[2022-05-28 18:05:04,102] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-05-28 18:05:04,121] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
